name: selections
version: 0.3.0.0
synopsis: Combinators for operating with selections over an underlying functor
description: See the [README on github](https://github.com/ChrisPenner/selections#readme)
  for tutorials!
category: Data Structures, Functors
author: Chris Penner
maintainer: christopher.penner@gmail.com
copyright: 2017 Chris Penner
license: BSD3
github: ChrisPenner/selections
extra-source-files:
- README.md
dependencies:
- base >=4.7 && <5
library:
  source-dirs: src
  exposed-modules:
  - Data.Functor.Selection
  - Control.Lens.Selection
